name: playoffs_score_card
repository: https://github.com/RemeJuan/playoffs_score_card
homepage: https://playoffs-score-tracker.pages.dev/
description: A simple app for users to track their progress across the F45 Playoffs.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.4.11

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.5
  cloud_firestore: 4.8.1
  hexcolor: 3.0.1
  flutter_hooks: 0.18.6
  intl: 0.18.1
  visibility_detector: 0.4.0+2
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  path_provider: 2.0.15
  firebase_core: 2.14.0
  firebase_app_check: 0.1.4+2
  chart_sparkline: 1.0.13
  flutter_file_saver: 0.6.2
  url_launcher: 6.1.11
  file_picker: 5.3.2
  package_info_plus: 4.0.2
  firebase_auth: 4.6.3
  hooks_riverpod: 2.3.6
  flutter_riverpod: 2.3.6
  rate_my_app: 2.0.0
  freezed: 2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.5
  isar_generator: 3.1.0+1
  cider: 0.1.6
  flutter_lints: 2.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: "Trade Gothic"
      fonts:
        - asset: "assets/fonts/Trade Gothic LT.ttf"
        - asset: "assets/fonts/Trade Gothic LT Bold.ttf"
          weight: 600
        - asset: "assets/fonts/Trade Gothic LT Light.ttf"
          weight: 300
cider:
  link_template:
    tag: https://github.com/RemeJuan/playoffs_score_card/releases/tag/%tag% # initial release link template
    diff: https://github.com/RemeJuan/playoffs_score_card/compare/%from%...%to% # subsequent releases link template